version: "3.8"

services:
  db:
      image: postgres:alpine3.17
      environment:
        - POSTGRES_USER=${PG_USER}
        - POSTGRES_PASSWORD=${PG_PASSWORD}
        - POSTGRES_DB=${PG_NAME}
      ports:
        - "${PG_PORT}:5432"
      volumes:
        - postgres-db:/var/lib/postgresql/data
      env_file:
        - .env
  web:
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./:/app
      - ./go.mod:/app/go.mod
    depends_on:
      - db

volumes:
  postgres-db:
